---
- hosts: db
  become: yes
  ignore_errors: yes
  gather_facts: true
  tasks:
     - name: check number of cpu
       command: uptime 
       register: nproc_output
     - name: display the output
       debug: 
         msg: nproc_output.stdout
     - name: create file
       file:
         path: /home/ec2-user/week3
         state: touch
         mode: '0644'
       register: file_output
     - name: display output
       debug:
         var: file_output.diff.after.path
      