---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: nation123
    group_name: devops
  vars_files:
    - variables.yml
  tasks:
    - name: check the time
      command: dateallyear
     ## when: ansible_distribution == "nation" or ansible_processor_nproc == 2
    - name: create user nation
      user:
         name: "{{user_name}}"
         comment: nation devopsEng 
    - name: create group
      group:
         name: "{{group_name}}"
         state: present
    - name: Install package
      package: 
        name: "{{pkg_name}}"
        state: present